### ISSUE TITLE
Crash in --smooth

### ISSUE THREAD

**Issue by Zahl** [gmcnew/bestofboth#5]
```minecraft@server:~/minecraft/bestofboth$ /usr/local/bin/python2.7 bestofboth.py --smooth /home/minecraft/world/
bestofboth version 0.3.2
(a tool for smoothing terrain discontinuities in Minecraft worlds)
http://github.com/gmcnew/bestofboth

examining edge 2817 of 12962...Traceback (most recent call last):
  File "bestofboth.py", line 1037, in <module>
    main()
  File "bestofboth.py", line 1030, in main
    smooth(worldDir, edgeFilePath)
  File "bestofboth.py", line 693, in smooth
    if erosionTask.run(level, treeDecayList, width):
  File "bestofboth.py", line 366, in run
    self.removeOrphanLeaves(level, chunk, x, z)
  File "bestofboth.py", line 102, in removeOrphanLeaves
    self.removeOrphanLeaf(level, x, z, y)
  File "bestofboth.py", line 70, in removeOrphanLeaf
    chunk = level.getChunk(fx / 16, fz / 16)
  File "/home/minecraft/bestofboth/pymclevel/infiniteworld.py", line 2002, in getChunk
    c = self._makeChunk(cx, cz)
  File "/home/minecraft/bestofboth/pymclevel/infiniteworld.py", line 1972, in _makeChunk
    raise ChunkNotPresent, (cx, cz);
pymclevel.mclevelbase.ChunkNotPresent: (-12, -123)```

**Comment by gmcnew** [comment]
Did you use a map editor to remove chunks after running the --find-edges step?

If not, this is simply a bug. As a workaround, you could explore the map and cause a chunk to be created at (-192, -1968) (which is what you get when you multiply chunk coordinates (-12, -123) by 16).

**Comment by Zahl** [comment]
Hi, I deleted chunks first using MCChunkDeleter, then ran --find-edges.. After that I started up the server again, explored a bit to make sure some new land is generated, stopped the server and did --smooth

I'll try what you suggested now and report back.

**Comment by Zahl** [comment]
Well, I repeated this 3 times now. It just keeps coming up with new missing chunks :-(
The funny part is that it even fails earlier after exploring more.
First, it failed at edge 2817 of 12962, now it fails at edge 8xx of 12962... But I noticed that it keeps changing the edges.txt, so that might be the reason for that.

**Comment by gmcnew** [comment]
bestofboth removes edges from edges.txt when they're smoothed. This would
explain why it's failing "earlier", although in "edge 8xx of 12962", you
should have seen a "total chunks" value (12962 here) which was smaller than
that of your first run.

Are you sure that you ran --find-edges -after- deleting chunks with
MCChunkDeleter?

I don't have time to provide much help on this issue, but I would be
interested to know what happens if you started over from the beginning,
without using MCChunkDeleter. It seems like the edges.txt file is referring
to chunks that no longer exist.

On Wed, Nov 30, 2011 at 8:32 AM, Zahl <
reply@reply.github.com

**Comment by Zahl** [comment]
I am quite sure that I didn't delete any chunks after running find-edges.
However, after running the chunk deleter, there were many little separated "islands" consisting of 3 or 4 chunks only, sometimes almost touching. Could that be an issue?
I do have a backup of the map from after deleting, so I could try again, just to make sure. But if you don't have time to investigate this issue currently I won't bother you too much, cause I used mcmerge now to do the job, so from my side this is not that important.
